version: '3'
services:
  db:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password" 

  release:
    build:
      context: ../.
      dockerfile: .docker/Dockerfile.release
    ports:
      - '4000:4000'
    environment: 
      COOKPOD_HOST: "localhost"
      PORT: "4000"
      SECRET_KEY_BASE: "4MdgbwNdUz9KtTKcNn5A3xRRMAPKJFDrrO9PH6uBuuLas/va/dTiEPYzkobGf8d/"
      LIVE_VIEW_SALT: "ZQIFgaHu"
      DB_NAME: "cookpod_dev"
      DB_HOSTNAME: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password" 
      BASIC_AUTH_USERNAME: "user"
      BASIC_AUTH_PASSWORD: "secret"

  prometheus:
    image: bitnami/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/app/prometheus.yml"
      - "--storage.tsdb.path=/opt/bitnami/prometheus/data"
      - "--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries"
      - "--web.console.templates=/opt/bitnami/prometheus/conf/consoles"
    volumes:
      - .:/app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes: 
  database:

