version: '3'
services:
  web:
    build: 
      context: ../.
      dockerfile: .docker/Dockerfile
    command: /app/.docker/run.sh  
    volumes:
      - ../.:/app:cached
    ports:
      - 4000:4000
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password" 

volumes: 
  database:

