on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.10.2
      
      - name: Get deps cache
        uses: actions/cache@v1
        with:
         path: deps/
         key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
         restore-keys: ${{ runner.os }}-deps-
      
      - name: Get build cache
        uses: actions/cache@v1 
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile

      - name: Check formatted
        run: mix format --check-formatted

      - name: Run static analysis
        run: mix credo

      - name: Run tests
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
          bash <(curl -s https://codecov.io/bash)

